package main

import (
	"fmt"
	"sort"
	"strings"
)

const (
	defaultCategory      = "Others"
	defaultTopicCategory = "others"
	textLengthLimit      = 200

	headerMarkdown = `<!--lint disable awesome-contributing awesome-license awesome-list-item match-punctuation no-repeat-punctuation no-undefined-references awesome-spell-check-->
# Awesome Stars [![Awesome](https://awesome.re/badge.svg)](https://github.com/sindresorhus/awesome)

> A curated list of my GitHub stars! Generated by [starred](https://github.com/maguowei/starred).

## Contents
`

	licenseTemplate = `## License

[![CC0](http://mirrors.creativecommons.org/presskit/buttons/88x31/svg/cc-zero.svg)](https://creativecommons.org/publicdomain/zero/1.0/)

To the extent possible under law, [%s](https://github.com/%s) has waived all copyright and related or neighboring rights to this work.
`
)

// htmlEscape replaces '<' and '>' with their HTML entity representations.
func htmlEscape(text string) string {
	var sb strings.Builder
	for _, r := range text {
		switch r {
		case '<':
			sb.WriteString("&lt;")
		case '>':
			sb.WriteString("&gt;")
		default:
			sb.WriteRune(r)
		}
	}
	return sb.String()
}

// cleanDescription cleans up the repo description, removes newlines,
// applies HTML entity escaping, and truncates to textLengthLimit characters.
func cleanDescription(raw string) string {
	if raw == "" {
		return ""
	}
	escaped := htmlEscape(raw)
	noNewlines := strings.ReplaceAll(escaped, "\n", "")
	trimmed := strings.TrimSpace(noNewlines)
	runes := []rune(trimmed)
	if len(runes) > textLengthLimit {
		runes = runes[:textLengthLimit]
	}
	return string(runes)
}

// makeAnchor converts category string to Markdown link anchor (e.g. "C++" -> "c++", "Jupyter Notebook" -> "jupyter-notebook").
func makeAnchor(category string) string {
	fields := strings.Fields(strings.ToLower(category))
	return strings.Join(fields, "-")
}

type repoItem struct {
	Name        string
	URL         string
	Description string
}

// GenerateMarkdown formats a list of repositories into awesome-stars markdown.
func GenerateMarkdown(username string, repos []Repository, sortByAlphabet, byTopic, includePrivate bool) string {
	var categoryOrder []string
	repoMap := make(map[string][]repoItem)

	addRepo := func(cat string, item repoItem) {
		if _, exists := repoMap[cat]; !exists {
			categoryOrder = append(categoryOrder, cat)
		}
		repoMap[cat] = append(repoMap[cat], item)
	}

	for _, s := range repos {
		if s.IsPrivate && !includePrivate {
			continue
		}

		desc := cleanDescription(s.Description)
		item := repoItem{
			Name:        s.NameWithOwner,
			URL:         s.URL,
			Description: desc,
		}

		if byTopic {
			categories := s.Topics
			if len(categories) == 0 {
				categories = []string{defaultTopicCategory}
			}
			for _, cat := range categories {
				addRepo(cat, item)
			}
		} else {
			cat := s.Language
			if cat == "" {
				cat = defaultCategory
			}
			addRepo(cat, item)
		}
	}

	if sortByAlphabet {
		sort.Strings(categoryOrder)
	}

	var sb strings.Builder
	sb.WriteString(headerMarkdown)

	// Table of Contents
	for _, cat := range categoryOrder {
		anchor := makeAnchor(cat)
		sb.WriteString(fmt.Sprintf("- [%s](#%s)\n", cat, anchor))
	}
	sb.WriteString("\n")

	// Categories and Repositories
	for _, cat := range categoryOrder {
		// Category header escaping '#' to '# #' (e.g. C# -> C# #)
		headerCat := strings.ReplaceAll(cat, "#", "# #")
		sb.WriteString(fmt.Sprintf("## %s \n\n", headerCat))
		for _, repo := range repoMap[cat] {
			sb.WriteString(fmt.Sprintf("- [%s](%s) - %s\n", repo.Name, repo.URL, repo.Description))
		}
		sb.WriteString("\n")
	}

	// License footer
	sb.WriteString(fmt.Sprintf(licenseTemplate, username, username))

	return sb.String()
}
